In [8]:
import numpy as np
import pandas as pd

WINDTURBINE_PRODUCED_YEARLY = 24_054_796.56
HOME_COUNT = 10
MEAN_PERSONS = 4
STD_PERSONS = 1
MIN_PERSONS = 1
MAX_PERSONS = 6

MONTHLY_USAGE_KWH = {
    ("apartment", 1): 121,
    ("house", 1): 183,
    ("apartment", 2): 188,
    ("house", 2): 258,
    ("apartment", 3): 246,
    ("house", 3): 325,
    ("apartment", 4): 292,
    ("house", 4): 383,
    ("apartment", 5): 342,
    ("house", 5): 442,
    ("apartment", 6): 383,
    ("house", 6): 500,
}

month_names = [
    "jan", "feb", "mar", "apr", "may", "jun",
    "jul", "aug", "sep", "oct", "nov", "dec",
]

rng = np.random.default_rng(42)
home_types = rng.choice(["house", "apartment"], size=HOME_COUNT)
persons = np.clip(
    np.rint(rng.normal(loc=MEAN_PERSONS, scale=STD_PERSONS, size=HOME_COUNT)).astype(int),
    MIN_PERSONS,
    MAX_PERSONS,
)

rows = []
for index, (home_type, person_count) in enumerate(zip(home_types, persons), start=1):
    avg_monthly_kwh = MONTHLY_USAGE_KWH[(home_type, int(person_count))]

    monthly_adjustments = []
    for month in range(1, 13):
        if month in (3, 4):
            adjustment = -0.15
        elif month in (12, 1, 2):
            adjustment = rng.uniform(0.00, 0.07)
        elif month in (6, 7, 8):
            adjustment = rng.uniform(-0.15, 0.15)
        else:
            adjustment = rng.uniform(-0.03, 0.03)
        monthly_adjustments.append(adjustment)

    monthly_usage = [avg_monthly_kwh * (1 + adjustment) for adjustment in monthly_adjustments]
    yearly_kwh = float(np.sum(monthly_usage))

    row = {
        "home_id": f"home_{index}",
        "home_type": home_type,
        "persons": int(person_count),
        "average_monthly_usage_kWh": avg_monthly_kwh,
        "yearly_usage_kWh": yearly_kwh,
    }

    for month_name, usage_value in zip(month_names, monthly_usage):
        row[f"{month_name}_usage_kWh"] = usage_value

    rows.append(row)

homes_df = pd.DataFrame(rows)

total_10home_yearly_usage_kwh = homes_df["yearly_usage_kWh"].sum()
energy_balance_kwh = WINDTURBINE_PRODUCED_YEARLY - total_10home_yearly_usage_kwh

print(f"Windturbine_Produced_Yearly: {WINDTURBINE_PRODUCED_YEARLY:,.2f} kWh")
print(f"Total yearly home usage (10 homes): {total_10home_yearly_usage_kwh:,.2f} kWh")
print(f"Energy balance: {energy_balance_kwh:,.2f} kWh")

homes_df

Windturbine_Produced_Yearly: 24,054,796.56 kWh
Total yearly home usage (10 homes): 41,420.61 kWh
Energy balance: 24,013,375.95 kWh

,home_id,home_type,persons,average_monthly_usage_kWh,yearly_usage_kWh,jan_usage_kWh,feb_usage_kWh,mar_usage_kWh,apr_usage_kWh,may_usage_kWh,jun_usage_kWh,jul_usage_kWh,aug_usage_kWh,sep_usage_kWh,oct_usage_kWh,nov_usage_kWh,dec_usage_kWh
0,home_1,house,3,325,3913.441748,330.169681,337.616804,276.25,276.25,316.494436,356.944039,337.837279,350.163555,322.163256,334.178611,332.665862,342.708225
1,home_2,apartment,4,292,3441.585053,295.978415,301.539777,248.20,248.20,284.007442,261.715760,308.035088,313.441165,300.190771,288.948460,289.730454,301.597721
2,home_3,apartment,4,292,3431.011434,295.872795,294.655596,248.20,248.20,291.574350,268.077259,306.875706,286.494508,297.828522,295.508645,288.712664,309.011390
3,home_4,house,4,383,4471.262017,404.575732,393.388295,325.55,325.55,378.135780,403.968733,341.607560,348.519452,371.679185,389.593522,386.788273,401.905484
4,home_5,house,3,325,3796.074351,342.761585,335.440334,276.25,276.25,326.340453,289.880207,287.416682,341.419289,324.436376,326.272104,330.167478,339.439842
5,home_6,apartment,5,342,3941.413712,355.252691,355.387419,290.70,290.70,337.977056,293.861910,335.507204,312.716387,340.123008,349.251831,336.540438,343.395768
6,home_7,house,5,442,5258.195209,450.706018,451.083791,375.70,375.70,446.294026,449.562463,479.644903,463.787975,439.517380,450.327821,433.168122,442.702712
7,home_8,apartment,4,292,3378.873753,293.840578,306.765025,248.20,248.20,291.332089,262.327408,292.091522,261.542540,295.439533,291.056658,289.915492,298.162907
8,home_9,house,5,442,5291.557129,461.500943,453.194482,375.70,375.70,431.064476,391.347583,503.247630,496.177800,447.296233,435.790871,454.442558,466.094553
9,home_10,house,4,383,4497.197289,402.219826,395.047382,325.55,325.55,377.766111,336.625322,429.259015,377.918696,376.160310,378.540883,384.820466,387.739278

In [22]:
import numpy as np
import pandas as pd

WINDTURBINE_PRODUCED_YEARLY = 24_054_796.56
HOME_COUNT = 5000
MEAN_PERSONS = 4
STD_PERSONS = 1
MIN_PERSONS = 1
MAX_PERSONS = 6

MONTHLY_USAGE_KWH = {
    ("apartment", 1): 121,
    ("house", 1): 183,
    ("apartment", 2): 188,
    ("house", 2): 258,
    ("apartment", 3): 246,
    ("house", 3): 325,
    ("apartment", 4): 292,
    ("house", 4): 383,
    ("apartment", 5): 342,
    ("house", 5): 442,
    ("apartment", 6): 383,
    ("house", 6): 500,
}

month_names = [
    "jan", "feb", "mar", "apr", "may", "jun",
    "jul", "aug", "sep", "oct", "nov", "dec",
]

rng = np.random.default_rng(42)
home_types = rng.choice(["house", "apartment"], size=HOME_COUNT)
persons = np.clip(
    np.rint(rng.normal(loc=MEAN_PERSONS, scale=STD_PERSONS, size=HOME_COUNT)).astype(int),
    MIN_PERSONS,
    MAX_PERSONS,
)

rows = []
for index, (home_type, person_count) in enumerate(zip(home_types, persons), start=1):
    avg_monthly_kwh = MONTHLY_USAGE_KWH[(home_type, int(person_count))]

    monthly_adjustments = []
    for month in range(1, 13):
        if month in (3, 4):
            adjustment = -0.15
        elif month in (12, 1, 2):
            adjustment = rng.uniform(0.00, 0.07)
        elif month in (4, 5, 9, 10):
            adjustment = rng.uniform(-0.15, 0.0)
        elif month in (6, 7, 8):
            adjustment = rng.uniform(-0.15, -0.05)    
        else:
            adjustment = rng.uniform(-0.03, 0.03)
        monthly_adjustments.append(adjustment)

    monthly_usage = [avg_monthly_kwh * (1 + adjustment) for adjustment in monthly_adjustments]
    yearly_kwh = float(np.sum(monthly_usage))

    row = {
        "home_id": f"home_{index}",
        "home_type": home_type,
        "persons": int(person_count),
        "average_monthly_usage_kWh": avg_monthly_kwh,
        "yearly_usage_kWh": yearly_kwh,
    }

    for month_name, usage_value in zip(month_names, monthly_usage):
        row[f"{month_name}_usage_kWh"] = usage_value

    rows.append(row)

homes_df = pd.DataFrame(rows)

monthly_columns = [f"{month_name}_usage_kWh" for month_name in month_names]
combined_monthly_usage_kwh = homes_df[monthly_columns].sum()

for month_name in month_names:
    print(f"{month_name}: {combined_monthly_usage_kwh[f'{month_name}_usage_kWh']:,.2f} kWh")

jan: 1,752,164.21 kWh
feb: 1,751,765.32 kWh
mar: 1,438,480.50 kWh
apr: 1,438,480.50 kWh
may: 1,565,116.40 kWh
jun: 1,522,588.21 kWh
jul: 1,523,151.08 kWh
aug: 1,523,324.26 kWh
sep: 1,564,995.01 kWh
oct: 1,565,316.25 kWh
nov: 1,692,342.98 kWh
dec: 1,752,415.58 kWh

In [23]:
# Total yearly usage for all homes in the current homes_df
total_all_homes_yearly_usage_kwh = homes_df["yearly_usage_kWh"].sum()

print(f"Total yearly usage for all homes: {total_all_homes_yearly_usage_kwh:,.2f} kWh")
total_all_homes_yearly_usage_kwh

Total yearly usage for all homes: 19,090,140.31 kWh

np.float64(19090140.30661267)

In [24]:
# Define homes shared energy usage from Cell 2 output
homes_shared_energy_usage = combined_monthly_usage_kwh.copy()

for month, value in homes_shared_energy_usage.items():
    print(f"{month}: {value:,.2f} kWh")

jan_usage_kWh: 1,752,164.21 kWh
feb_usage_kWh: 1,751,765.32 kWh
mar_usage_kWh: 1,438,480.50 kWh
apr_usage_kWh: 1,438,480.50 kWh
may_usage_kWh: 1,565,116.40 kWh
jun_usage_kWh: 1,522,588.21 kWh
jul_usage_kWh: 1,523,151.08 kWh
aug_usage_kWh: 1,523,324.26 kWh
sep_usage_kWh: 1,564,995.01 kWh
oct_usage_kWh: 1,565,316.25 kWh
nov_usage_kWh: 1,692,342.98 kWh
dec_usage_kWh: 1,752,415.58 kWh

In [36]:
import numpy as np
import pandas as pd
from IPython.display import HTML, display

month_day_counts = {
    "jan": 31,
    "feb": 28,
    "mar": 31,
    "apr": 30,
    "may": 31,
    "jun": 30,
    "jul": 31,
    "aug": 31,
    "sep": 30,
    "oct": 31,
    "nov": 30,
    "dec": 31,
}

if "homes_shared_energy_usage" in globals():
    monthly_totals = homes_shared_energy_usage
elif "combined_monthly_usage_kwh" in globals():
    monthly_totals = combined_monthly_usage_kwh
else:
    raise NameError("Run Cell 2 (or Cell 4) first to create monthly totals.")

rng = np.random.default_rng(42)

daily_usage_by_month = {}
rows = []

for month, day_count in month_day_counts.items():
    monthly_key = f"{month}_usage_kWh"
    month_total = float(monthly_totals[monthly_key])

    random_weights = rng.random(day_count)
    daily_values = (random_weights / random_weights.sum()) * month_total

    daily_values = np.round(daily_values, 2)
    correction = np.round(month_total - daily_values.sum(), 2)
    daily_values[-1] = np.round(daily_values[-1] + correction, 2)

    month_df = pd.DataFrame({
        "month": month,
        "day": np.arange(1, day_count + 1),
        "usage_kWh": daily_values,
    })

    daily_usage_by_month[month] = month_df
    rows.append(month_df)

all_daily_usage = pd.concat(rows, ignore_index=True)
january_daily_usage = daily_usage_by_month["jan"]

scrollable_html = (
    '<div style="max-height: 500px; overflow-y: auto; border: 1px solid #ddd;">'
    + all_daily_usage.to_html(index=False)
    + "</div>"
)

In [33]:
# Build a daily timeline for 2025 and let month update automatically in the loop
from IPython.display import HTML, display

simulation_daily_demand = all_daily_usage.copy()
simulation_daily_demand["date"] = pd.date_range("2025-01-01", "2025-12-31", freq="D")

# Example simulation loop (replace placeholder logic with battery/wind logic later)
daily_demand_rows = []

for row in simulation_daily_demand.itertuples(index=False):
    current_date = row.date
    homes_shared_energy_usage_kwh_day = float(row.usage_kWh)

    daily_demand_rows.append({
        "date": current_date.strftime("%Y-%m-%d %H:%M:%S"),
        "homes_shared_energy_usage_kWh": homes_shared_energy_usage_kwh_day,
    })

simulation_df = pd.DataFrame(daily_demand_rows)

scrollable_html = (
    '<div style="max-height: 500px; overflow-y: auto; border: 1px solid #ddd;">'
    + simulation_df.to_html(index=False)
    + "</div>"
 )
display(HTML(scrollable_html))

In [37]:
simulation_df.to_excel("Daily_Usage_Homes.xlsx", index=False)